config/routes.rb
Solar::Application.routes.draw do

  resources :checklist_items

  devise_for :users
  
  resources :users, only: [:show, :update] do
    collection do 
      get :billing
      get :subscribe
      put :create_subscription
      put :unsubscribe
      get :edit_card
      put :update_card
      post :read_message
    end
  end

  resources :manuals do
    post :single_charge
    get :duplicate
    get :installer_signature
    get :contractor_signature
    get :signature_success
  end
  
  resources :invoices, :controller => "eway_payments", :only => [:show]
  
  resources :eway_payments, only: [:create]
  
  resources :images, only: [:destroy]
  resources :pdfs, only: [:destroy]
  
  put '/manuals/:id/document', to: 'manuals#document', as: "manual_document"
  
  put '/images/:id/set_feature', :to => 'images#set_feature', :as => 'set_feature'
  
  authenticated :user do
    root :to => "manuals#new"
  end
  
  get '/faq', to: 'home#faq'  
  get '/privacy', to: 'home#privacy'
  get '/delivery', to: 'home#delivery'
  get '/refunds', to: 'home#refunds'
  get '/terms', to: 'home#terms'
  get '/admin_info', to: 'admin#admin_info'

  root :to => 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  attr_protected :insider, :eway_id, :subscribed

  has_attached_file :logo, LOGO_OPTS
  validates_attachment :logo,
    :size => { :in => 0..2.megabytes }

  attr_accessor :current_password, :cc_number, :cc_expiry_month, :cc_expiry_year, :cvn, :remember, :validate_card, :terms

  validates :cc_number, :length => { :is => 16 }, :if => :should_validate_card?
  validates :cc_expiry_month, :length => { :is => 2 }, :if => :should_validate_card?
  validates :cc_expiry_year, :length => { :is => 2 }, :if => :should_validate_card?
  validates :cvn, :length => { :in => 3..4 }, :if => :should_validate_card?

  def should_validate_card?
    validate_card
  end

  validates_presence_of :first_name, :last_name

  validate :agree_terms, :on => :create

  def agree_terms
    unless terms == '1'
      errors[:terms] = "You must agree."
    end
  end

  has_many :manuals
  has_many :eway_payments

  has_many :pdfs
  accepts_nested_attributes_for :pdfs

  has_and_belongs_to_many :messages

  after_create :send_welcome_mail

  def unread_message
    if messages.count > 0
      return Message.where('id NOT IN (?)', messages).first
    end
    Message.first
  end

  def flash_message
    if unread_message
      return {unread_message.flashtype.to_sym => [unread_message.id, unread_message.content.html_safe]}
    end
  end

  def active_manuals
    manuals.where(:trashed => false).order('install_date DESC').includes(:eway_payment)
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def full_address
    "#{company_address} #{company_suburb} #{company_postcode}"
  end

  def subscribed?
    subscribed
  end

  def fields_filled?
    !fields_not_filled?
  end

  def fields_not_filled?
    [company, accreditation, abn, company_address, company_suburb, company_postcode, contact_email, company_phone].each do |field|
      return true if field.blank?
    end
    false
  end

  def update_with_password(params={})
    if params[:password].blank?
      params.delete(:password)
      params.delete(:current_password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end
    update_attributes(params)
  end

  def is_new?
    manuals.count == 0
  end

  def pdfs_array=(array)
    array.each do |file|
      pdfs.build(:file => file)
    end
  end

  def unpaid_marked_manuals
    manuals.where(:marked => true).reject(&:paid?)
  end

  def billable_manuals(number)
    ms = number - FREE_MANUALS
    ms < 0 ? 0 : ms
  end

  def manuals_charge(number)
    billable_manuals(number) * SUBSCRIPTION_MANUAL_FEE
  end

  def current_charge
    charge = manuals_charge(billable_manuals(unpaid_marked_manuals.count))
    charge + SUBSCRIPTION_FEE
  end

  # payments

  def self.billable
    where(:subscribed => true).where('last_payed_at <= ?', SUBSCRIPTION_INTERVAL.ago).where('eway_id IS NOT NULL').where(:insider => false)
  end

  def is_billable?
    User.billable.include?(self)
  end

  def first_manual
    manuals.order('created_at ASC').first
  end

  def is_first_manual?(manual)
    if manuals.count > 0
      return manual.id == first_manual.id
    end
    return true
  end

  def create_eway_id
    self.eway_id = Eway.client.create_customer(
      'CustomerRef' => self.id,
      'Title' => 'Mr.',
      'FirstName' => first_name,
      'LastName' => last_name,
      'Company' => '',
      'Country' => 'au',
      'Email' => '',
      'Address' => '',
      'Suburb' => '',
      'State' => '',
      'PostCode' => '',
      'Phone' => '',
      'Mobile' => '',
      'Fax' => '',
      'URL' => '',
      'JobDesc' => '',
      'Comments' => '',
      'CCNumber' => cc_number,
      'CCNameOnCard' => '',
      'CCExpiryMonth' => cc_expiry_month,
      'CCExpiryYear' => cc_expiry_year
    )

    if remember == '1'
      self.save
    end

    return self.eway_id
  end

  def stored_cc_number
    self[:stored_cc_number] || get_cc_number
  end

  def flag!
    self.flagged = true
    self.save
  end

  private

  def get_cc_number
    if !eway_id
      return nil
    end
    response = Eway.client.query_customer(eway_id)
    self.stored_cc_number = response['CCNumber']
    self.save
    return self.stored_cc_number
  end

  def send_welcome_mail
    UserMailer.welcome(self).deliver
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  skip_before_filter :check_user_flagged!
  before_filter :authenticate_user!
  
  rescue_from BigCharger::Error do |e|
    flash[:alert] = e.message
    redirect_to edit_card_users_path
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  # only for logo (probably)
  def update
    @user = User.find(params[:id])
    unless @user.update_attributes(params[:user])
      flash[:alert] = "There was a problem with the image, please try another."
    end
    
    # upload PDF form redirects to manual/:id
    if params[:redirect]
      redirect_to params[:redirect]
    else
      redirect_to root_url
    end
  end
  
  def edit_card
    @user = current_user
  end
  
  def update_card
    @user = current_user
    @user.assign_attributes(params[:user])
    @user.validate_card = true    
    # validate card details
    unless @user.valid?
      render action: "edit_card" and return
    end
    
    # this should only be for users whose monthly payment failed
    if @user.create_eway_id
      if @user.flagged && @user.is_billable?
        @payment = EwayPayment.new
        @payment.user = @user
        unless @payment.process_subscription!
          flash[:alert] = "Payment failed: #{@payment.errors[:base].first}"
          redirect_to root_url and return
        end
      end
      @user.flagged = false
      @user.stored_cc_number = nil
      @user.save
      redirect_to root_url, :notice => "Payment details updated."
    else
      redirect_to root_url
    end
  end
  
  def billing
    @user = current_user
    @payments = @user.eway_payments.reverse
    @payments_months = @payments.group_by{ |p| p.created_at.beginning_of_month }.sort.reverse!.first(12)
    
    if @payments_months.size > 0
      month = @payments_months.last.first
    
      # fill out remainder of year with empty values
      (12 - @payments_months.size).times do
        month -= 1.month
        @payments_months << [month, []]
      end
    end
  end
  
  def subscribe
    @user = current_user
  end
  
  def create_subscription
    @user = current_user
    @user.subscribed = true
    
    if params[:user]
      @user.assign_attributes(params[:user])
      @user.validate_card = true
      unless @user.valid?
        @user.subscribed = false
        flash[:alert] = "Invalid credit card"
        render action: 'subscribe' and return
      end
    end
    
    @user.eway_id ||= @user.create_eway_id
    
    # so we know to first charge them in a month
    @user.last_payed_at = Time.now
    
    @user.save
    redirect_to root_url, :notice => "You have successfully subscribed."
  end
  
  def unsubscribe
    @user = current_user
    
    unless @user.last_payed_at.nil?
      @payment = EwayPayment.new
      @payment.user = @user
      unless @payment.process_subscription!
        flash[:alert] = "Payment failed: #{@payment.errors[:base].first}. You have not been unsubscribed. Please update your credit card details and try again."
        redirect_to edit_card_users_path and return
      end
    end
    
    @user.subscribed = false
    @user.save
    redirect_to root_url, :notice => "You have unsubscribed."
  end

  def read_message
    @user = current_user
    message = Message.find(params[:message_id])
    @user.messages << message
    render nothing: true
  end
  
end

app/views/users/_logo.html.erb
<div id="logo-holder">
  <div id="logo-upload">
  <%= link_to "#", :id => "upload-logo-btn", class: current_user.logo? ? "gotlogo" : "nologo" do  %>
    <% if current_user.logo? %>
     <%= image_tag current_user.logo(:thumb) %>
     <span class="edit-logo">Update<br/>Logo</span>
    <% else %>
     Add<br/>Your<br/>Logo
    <% end %>  
  <% end %>
  </div>
</div>

<div id="logo-submit">
  <p class="help">Hit 'Browse' below to search your computer for your new logo file in JPG or PNG format. Please ensure your logo's file size is less than 2 megabytes.</p>
  <%= form_for current_user, :html => { :class => "logo-form" } do |f| %>
    <%= f.file_field :logo %>
    <%= f.submit "Update Logo" %>
  <% end %>
</div>  

app/views/users/billing.html.erb
<% unless current_user.insider %>  
  <% if current_user.subscribed? %>
    <p>
      You are subscribed. <%= link_to "Unsubscribe", unsubscribe_users_path, :method => :put, :confirm => "You will be charged for your current usage of #{strip_tags(currency(current_user.current_charge))}.\n\nAre you sure you want to unsubscribe?".html_safe %><br/>
      <span class="regular">Your next charge will be</span> <%= currency(current_user.current_charge) %> <span class="regular">on <%= nicetime(current_user.last_payed_at + 1.month) %></span>
    </p>
    <p>
      <% if @user.eway_id %>
        <span class="regular">Stored Card</span> 
        <%= format_card(@user.stored_cc_number) %><br/>
        <%= link_to "Change credit card", edit_card_users_path %>
      <% end %>
    </p>
  <% else %>
    <p>You are registered as a casual user. <%= link_to "Subscribe now", subscribe_users_path %></p>
  <% end %>
  
  <% if @payments_months.size > 0 %>
  
    <div id="invoice-graph">
      <% @payments_months.each_with_index do |month, index| %>
    
        <% date, payments = month %>
        <% total = payments.map(&:return_amount).inject(:+) %>
      
        <%= link_to '#', :class => 'month', 'data-count' => total, 'data-month' => date.strftime('%B') do %>
          <span class="info">
            <%= date.strftime('%B') %><br/>
            <%= currency(total || 0) %>
          </span>
        <% end %>
      <% end %>
    </div>
  
    <h4>Invoices</h4>
    <div id="invoices">
      <% @payments_months.each do |month, payments| %>
        <% if payments.size > 0 %>
          <%= link_to month.strftime('%B'), '#', :class => 'month', 'data-month' => month.strftime('%B') %>
          <div class="invoices-list" data-month='<%= month.strftime("%B") %>'>
            <table class="table">
              <tr>
                <th>Date</th>
                <th>Qty</th>
                <th>Type</th>
                <th>Total</th>
              </tr>
              <% payments.each do |payment| %>
                <tr>
                  <td><%= link_to payment.created_at.strftime('%B %-d'), invoice_path(payment), :target => '_blank' %></td>
                  <td><%= link_to payment.manuals.count, invoice_path(payment), :target => '_blank' %></td>
                  <td><%= link_to (payment.subscription ? 'Subscription' : 'One-off'), invoice_path(payment), :target => '_blank' %></td>
                  <td><%= link_to currency(payment.return_amount), invoice_path(payment), :target => '_blank' %></td>
                </tr>
              <% end %>
            </table>
          </div>
        <% end %>
      <% end %>
    </div>
    
  <% else %>
    <p>You have no invoices to display.</p>
  <% end %>
  
<% end %>
  

app/views/users/edit_card.html.erb
<%= form_for current_user, :url => update_card_users_path, :html => { :class => "card_form" } do |f| %>
  <% if current_user.flagged && current_user.is_billable? %>
    <p>
      We will try to reprocess the last payment with the new details.<br/>
      <strong>Total:</strong> <%= currency(current_user.current_charge) %>
    </p>
  <% end %>
  <div class="nest">
    <%= render :partial => "shared/cc_fields", :locals => {f: f} %>
    <div class="actions"><%= f.submit "Update Details", :class => "btn" %></div>
  </div>
<% end %>

app/views/users/subscribe.html.erb
<div class="nest">
  <div id="subscribe">
    <p>You are registered as a casual user. We recommend subscribing if you are producing more than six user manuals per month.</p>
    
    <dl>
      <dt>Casual Rates</dt>
      <dd>
        <%= currency(CASUAL_FEE) %> <span class="help">Per Manual</span><br/>
        No on-going fees
      </dd>
    </dl>
        
    <dl>
      <dt>Subscription Rates</dt>
      <dd>
        <%= currency(SUBSCRIPTION_MANUAL_FEE) %> <span class="help">Per Manual</span><br/>
        <%= currency(SUBSCRIPTION_FEE) %> monthly fee<br/>
        <span class="regular"><%= FREE_MANUALS %> free manuals per month</span>
      </dd>
    </dl>
    
    <p class="regular">
      <strong>First 30 days free</strong><br/>
      If you subscribe today you will not be billed until <%= nicetime(Time.now() + 1.month) %>.
    </p>
    
    <p class="regular">
      <strong>Cancellation</strong><br/>
      If you choose to cancel your subscription, you will be billed for the month in which you cancel.
    </p>
    
    <% if @user.eway_id %>
      <dl>
        <dt>Stored Card</dt>
        <dd><%= @user.full_name %><br/>
        <%= format_card(@user.stored_cc_number) %><br/>
        <%= link_to "Change credit card", "#", :class => "show-cc-fields" %>
        <%= link_to "Use this card", "#", :class => "hide-cc-fields" %>
        </dd>
      </dl>
    <% end %>
    
    <div id="subscribe-cc-fields" class="<%= @user.eway_id ? 'hidden' : '' %> nest">
      <%= form_for current_user, :url => create_subscription_users_path do |f| %>
        <%= render :partial => "shared/cc_fields", :locals => {f: f} %>
        <%= f.hidden_field :remember, :value => true %>
        
        <div class="actions">
          <%= f.submit "Subscribe" %>
        </div>
      <% end %>
    </div>
    <div class="nest">
      <div class="actions">
        <% if @user.eway_id %>
          <%= link_to "Subscribe Now", create_subscription_users_path, :method => :put, :class => "btn subscribe-now" %>
        <% end %>
      </div>
    </div>
  </div>
</div>