config/routes.rb
Solar::Application.routes.draw do

  resources :checklist_items

  devise_for :users
  
  resources :users, only: [:show, :update] do
    collection do 
      get :billing
      get :subscribe
      put :create_subscription
      put :unsubscribe
      get :edit_card
      put :update_card
      post :read_message
    end
  end

  resources :manuals do
    post :single_charge
    get :duplicate
    get :installer_signature
    get :contractor_signature
    get :signature_success
  end
  
  resources :invoices, :controller => "eway_payments", :only => [:show]
  
  resources :eway_payments, only: [:create]
  
  resources :images, only: [:destroy]
  resources :pdfs, only: [:destroy]
  
  put '/manuals/:id/document', to: 'manuals#document', as: "manual_document"
  
  put '/images/:id/set_feature', :to => 'images#set_feature', :as => 'set_feature'
  
  authenticated :user do
    root :to => "manuals#new"
  end
  
  get '/faq', to: 'home#faq'  
  get '/privacy', to: 'home#privacy'
  get '/delivery', to: 'home#delivery'
  get '/refunds', to: 'home#refunds'
  get '/terms', to: 'home#terms'
  get '/admin_info', to: 'admin#admin_info'

  root :to => 'home#index'

end

app/models/manual.rb
class Manual < ActiveRecord::Base
  
  attr_protected :marked
  
  validates_presence_of :client_address, :client_name, :client_suburb, :client_state_id, :install_date, :client_postcode, :if => :not_duplicate?
  
  validates_numericality_of :system_pv_current, :system_pv_voltage, :system_watts, :inverter_output, :inverter_number, :if => :validate_pdf_fields?, :allow_blank => true
  
  belongs_to :user
  
  belongs_to :eway_payment
  
  has_many :images, :dependent => :destroy
  accepts_nested_attributes_for :images
  
  belongs_to :client_state, :class_name => "State"
  
  has_and_belongs_to_many :pdfs
  
  has_many :panel_strings, :dependent => :destroy
  accepts_nested_attributes_for :panel_strings, :allow_destroy => true
  
  accepts_nested_attributes_for :user
  
  has_and_belongs_to_many :checklists
  
  has_many :checklist_responses, :dependent => :destroy
  has_many :checklist_items, :through => :checklist_responses
  
  accepts_nested_attributes_for :checklist_responses  
  
  attr_accessor :payment, :prefill_id, :duplicate
  
  after_save :build_strings, :send_signature_emails
  
  belongs_to :installer_signature, :class_name => "Signature"
  belongs_to :contractor_signature, :class_name => "Signature"
  
  accepts_nested_attributes_for :installer_signature
  accepts_nested_attributes_for :contractor_signature
  
  def build_strings
    panel_strings.build unless panel_strings.count > 0
  end
  
  # steps
  
  def steps
    %w{customer panels inverter warranties performance wiring checklist signature} + (user.subscribed? || paid? || user.insider || user.manuals.count == 0 ? [] : %w{payment})
  end
  
  def step_index(step)
    steps.index(step)
  end
  
  def past_step?(step)
    current_step_index < step_index(step)
  end
  
  def before_step?(step)
    current_step_index > step_index(step)    
  end
  
  def before_or_equal_step?(step)
    current_step_index >= step_index(step)    
  end
  
  def current_step_index
    step_index(current_step) || 99
  end
  
  def current_step?(step)
    current_step == step
  end
  
  def last_step?
    current_step == steps.last
  end
  
  def next_step
    steps[current_step_index + 1]
  end
  
  def step_back
    self.current_step = steps[current_step_index - 1]
  end

  def preview_detail(step)
    {
      "customer" => client_name,
      "panels" => "#{panels_watts}W #{panels_brand} #{panels_model}",
      "inverter" => "#{inverter_brand} #{inverter_series} #{inverter_model}",
      "warranties" => [warranty_inverter, warranty_panels_output_performance, warranty_panels_product, warranty_workmanship].join(", "),
      "performance" => (include_performance ? "#{sunlight_city.capitalize}, #{(performance_multiplier * 100).to_i}%" : 'No'),
      "wiring" => (include_wiring ? 'Yes' : 'No'),
      "checklist" => (include_checklist ? 'Included' : 'Manually complete & include'),
      "signature" => (installer_signature_id ? 'Signed' : 'Not Signed')
    }[step]
  end
  
  
  
  # dynamic fields
  
  # number of panels in each string
  def total_panels
    panel_strings.map{|string| (string.number || 0) }.inject(:+)
  end
  
  def total_array_size
    (total_panels || 0) * (panels_watts || 0) # whiny nils throw exception
  end
  
  def string_config
    panel_strings.map { |string|
      "<b>1 string of #{string.number} panels, #{string.volts} Volts DC, #{string.amps} Amps</b>"
    }.join("\n")
  end
  
  def display_address
    "#{client_address}"
  end
  
  def feature_image
    Image.where(manual_id: id, feature: true).first
  end
  
  def panels_serials
    panels_serial_numbers.split(',').map{ |number| number.strip }
  end
  
  def inverters_serials
    (inverter_serial || "").split(',').map{ |number| number.strip }
  end
  
  def table_from_csv(csv)
    buffer = ""
    index = 1
    line_text = ""
    csv.each do |number|
      line_text += "|#{index}. <b>#{number}</b>"
      if index % 3 == 0
        buffer << "#{line_text}|\n"
        line_text = ""
      end
      index += 1
    end
    buffer << "#{line_text}|" unless line_text.blank?
    buffer
  end
  
  def panels_table
    table_from_csv(panels_serials)
  end
  
  def inverters_table
    table_from_csv(inverters_serials)
  end
  
  # 
  
  def self.not_trashed
    where(:trashed => false)
  end
  
  def self.all_completed
    Manual.all.keep_if(&:completed?)
  end
  
  
  def validate_pdf_fields?
    paid? && !trashed && filled
  end
  
  def free_one?
    user.is_first_manual?(self)
  end
  
  def paid?
    (!!eway_payment) || free_one?
  end
  
  def unlocked?
    paid? || user.subscribed? || user.insider
  end
  
  def filled?
    paid? || filled || current_step.nil?
  end
  
  
  def marked?
    marked && user.subscribed?
  end
  
  def files_array=(array)
    array.each do |file|
      images.build(:file => file)
    end
  end
  
  # [ {key: 10%, value: 0.10}, {key: 15%, value: 0.15}, ... , {key: 100%, value: 1.0}]
  def multipliers
    (10..100).step(5).map{|n| ["#{n}%", (n / 100.0)] }
  end
  
  # signatures
  
  def installer_name
    (installer_signature && installer_signature.name) || (user && user.full_name)
  end
  
  def installer_accreditation
    (installer_signature && installer_signature.licence) || (user && user.accreditation)
  end
  
  def send_signature_emails  
    if installer_signature_email_changed? && installer_signature_email.present?
      SignatureMailer.installer_signature_request(self, installer_signature_email).deliver
    end
  end
  
  def warranty_workmanship
    append_years(self[:warranty_workmanship])
  end
    
  def warranty_panels_product
    append_years(self[:warranty_panels_product])
  end
  
  def warranty_panels_output_performance
    append_years(self[:warranty_panels_output_performance])
  end
  
  def warranty_inverter
    append_years(self[:warranty_inverter])
  end
  
  private
  
  def self.all_present?(array)
    array.each do |v|
      return false if v.blank?
    end
    true
  end
  
  def not_duplicate?
    !duplicate
  end
  
  def append_years(str)
    is_numeric = true if Float(str) rescue false
    if is_numeric
      return str + " years"
    end
    str
  end
  
end

app/controllers/manuals_controller.rb
class ManualsController < ApplicationController
  layout "pdf", :only => [:document]
  layout "blank", :only => [:installer_signature, :contractor_signature, :signature_success]
  
  rescue_from BigCharger::Error do |e|
    flash[:alert] = e.message
    redirect_to :back
  end
  
  before_filter :authenticate_user!, :except => [:installer_signature, :signature_success, :update]
  load_and_authorize_resource :except => [:installer_signature, :signature_success, :update]
  
  def document
    @manual = Manual.find(params[:id])
    
    
    @manual.assign_attributes(params[:manual])
    
    if @manual.user.subscribed?
      @manual.marked = true
      @manual.save
    end

    respond_to do |format|
      format.html
      format.pdf do
        pdf = DocumentPdf.new({ :page_size => 'A4' }, @manual)
        
        send_data pdf.render, filename: "#{@manual.client_name.downcase.squish.gsub( /\s/, '_' )}_gridconnect_user_manual.pdf",
          type: "application/pdf",
          disposition: "attachment"
      end
    end
  end
  
  def index
    @manuals = current_user.active_manuals

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @manuals }
    end
  end

  # GET /manuals/1
  # GET /manuals/1.json
  def show
    @payment = EwayPayment.new
    @maunal = Manual.find(params[:id])
    
    if @manual[:filled] && !@manual.paid?
      @manual.current_step = "payment"
    end
    
    if params[:step]
      @manual.current_step = params[:step]
    end
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @manual }
    end
  end

  # GET /manuals/new
  # GET /manuals/new.json
  def new
    @manual = Manual.new
    @manual.user = current_user
    @manual.panel_strings.build
    
    @manual.current_step = @manual.steps.first
    
    @all_manuals = current_user.manuals.keep_if(&:filled)
  end

  # GET /manuals/1/edit
  def edit
    @manual = Manual.find(params[:id])
    if params[:step]
      @manual.current_step = params[:step]
    end
    
    @manual.panel_strings.build unless @manual.panel_strings.count > 0
    
    @all_manuals = current_user.manuals.keep_if(&:filled)
  end

  # POST /manuals
  # POST /manuals.json
  def create
    @manual = Manual.new(params[:manual])
    @manual.user = current_user
    if @manual.save
      if @manual.filled
        redirect_to @manual, notice: 'Manual was successfully created.'
      else
        flash[:notice] = 'Your manual has been saved and been added to "My Installs".'
        render action: "new"
      end
    else
      @manual.step_back
      render action: "new"
    end
  end

  # PUT /manuals/1
  # PUT /manuals/1.json
  def update
    @manual = Manual.find(params[:id])
    
    if params[:manual]
      # extract user params since we don't want to assign with assign_attributes
      user_params = params[:manual].delete(:user)
    end
    
    @manual.assign_attributes(params[:manual])
    
    # payment step
    if params[:payment]
      # don't process payment if one exists (when you hit refresh)
      unless @manual.eway_payment
        # new credit card entered
        if user_params && params[:new_card] == '1'
          @manual.user.assign_attributes(user_params)
          @manual.user.validate_card = true
          # can't rely on normal save validating since we don't necessarily want to keep eway_id
          unless @manual.user.valid?
            @manual.current_step = "payment"
            flash[:alert] = "Invalid credit card details."
            render 'edit'
            return
          end
          @manual.user.create_eway_id
       end
      
        @manual.eway_payment = EwayPayment.process_single_payment!(@manual.user)
        
        # forget eway_id
        if params[:new_card] == '1' && @manual.user.remember == '0'
          @manual.user.eway_id = nil
        end
      end
    end
    
    if @manual.valid? && @manual.filled
      @manual.current_step = nil
    end
    
    respond_to do |format|
      if @manual.save
        if params[:manual] && params[:manual][:installer_signature_attributes]
          format.html { redirect_to manual_signature_success_path(@manual) }
        elsif @manual.filled
          format.html { redirect_to @manual, notice: 'Manual was successfully updated.' }
          format.json { head :no_content }
          format.js
        else
          format.html { render action: "edit" }
          format.js
        end
      else
        format.html { render action: "edit" }
        format.json { render json: @manual.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manuals/1
  # DELETE /manuals/1.json
  def destroy
    @manual = Manual.find(params[:id])
    @manual.trashed = true
    @manual.save
    puts @manual.errors.inspect
    respond_to do |format|    
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end
  
  def duplicate
    @to_dup = Manual.find(params[:manual_id])
    @manual = @to_dup.dup
    @manual.assign_attributes({
      :client_name => "",
      :client_address => "",
      :client_suburb => "",
      :client_postcode => "",
      :install_date => Time.now,
      :filled => false,
      :eway_payment => nil,
      :created_at => Time.now,
      :updated_at => Time.now,
      :current_step => 'customer',
      :installer_signature_id => nil,
      :installer_signature_email => nil,
      :panels_serial_numbers => nil,
      :inverter_serial => nil
    })
    
    @to_dup.panel_strings.each do |ps|
      @manual.panel_strings << ps.dup
    end
    
    @manual.marked = false
    @manual.duplicate = true
    
    if @manual.save
      redirect_to @manual, :notice => "Manual was duplicated. Fill in new customer details and check over the fields to complete."
    else
      redirect_to manuals_path, :alert => @manual.errors.full_messages.join(" ")
    end
  end
  
  
  def installer_signature
    @manual = Manual.find(params[:manual_id])
    @manual.build_installer_signature
  end
  
  def signature_success
    @manual = Manual.find(params[:manual_id])
  end
  
end

app/helpers/manuals_helper.rb
module ManualsHelper

end

app/views/manuals/_form.html.erb
<ol id="manual-form">
  <% @manual.steps.each do |step| %>
    <%= content_tag :li, :class => @manual.current_step?(step) ? 'step current' : (@manual.past_step?(step) ? 'step after' : 'step') do %>
      
      <span class="step-title"><%= step.capitalize %></span>
      
      <div class="step-inner">
      
        <% if (@manual.id && @manual.before_step?(step)) || (@manual.id && @manual.filled) %>
        
          <% unless @manual.current_step?(step) %>
            <div class="edit-step"><%= link_to "Edit", edit_manual_path(@manual, :step => step), :class => "btn" %></div>
          <% end %>
        <% end %>
    
        <% if (@manual.before_step?(step) || @manual.filled) && !@manual.current_step?(step) %>
          <span class="step-preview">
            <%= @manual.preview_detail(step) %>
          </span>
        <% end %>
        
        <%= form_for(@manual) do |f| %>
            <% if @manual.filled %>
              <%= f.hidden_field :current_step, :value => step %>
            <% else %>
              <% if @manual.last_step? %>
                <%= f.hidden_field :filled, :value => 1 %>
                <%= f.hidden_field :current_step, :value => "" %>
              <% else %>
                <%= f.hidden_field :current_step, :value => @manual.next_step %>
              <% end %>
            <% end %>
            
            <%= f.hidden_field :prefill_id %>
            
            <div class="step-fields nest">
              
              <%= render "step_#{step}", f: f %>
          
              <div class="actions">
                  <%= f.submit (@manual.filled ? "Save" : "Save & Continue"), :class => "primary" %>
              </div>
            </div>   
        <% end %>
     </div> 
    <% end # li %>
  
  <% end %>
</ol>

app/views/manuals/_images.html.erb
<div id="image-uploads">
  <%= form_for @manual, :url => { :action => :update }, :html => { :multipart => true } do |f| %>
    <p>Attach Installation Images <i class="icon-picture"></i><br/>
      <% if @manual.images.count > 0 %>
        <span class="help">Click to set a cover image - this image will appear on the front page of your manual</span>
      <% end %>
    </p>
    <%= f.file_field :files_array, :multiple => true,  :accept => "image/*" %>
    <%= f.submit "Add Images", :class => "btn", :id => "submit_manual_images_btn" %>
  <% end %>


  <div id="manual-images-container">
    <div id="manual-images">
      <% @manual.images.each do |image| %>
        <%= render :partial => 'manuals/image', :locals => { image: image } %>
      <% end %>
    </div>
  </div>
  <a href="#" id="upload-manual-images" class="btn">Add Images</a>
</div>

app/views/manuals/_serial_range.html.erb
<div class="serial-range">
  <p class="help">Enter a range of serials<br/>and press enter.</p>
  <label>From</label><input class="range-from" type="text" /><br/>
  <label>To</label><input class="range-to" type="text" />
</div>

app/views/manuals/_step_checklist.html.erb
<div class="checklist-container">
  	
	<div class="field">
	  <div class="field-label">
	    <%= f.label :include_checklist, "Complete paperless GC Installation & Comissioning checklist?" %>
	  </div>
	  <div class="field-input">
	    <%= f.check_box :include_checklist, :class => 'include-checklist' %>
		<p class="help">If you do not complete the checklist here online you will need to download this document <a href="http://www.solaraccreditation.com.au/installerresources/formsandchecklists.html" title="Download GC Installation & Checklist Manual">here</a>. Then manaully complete this document and attach it to your user manual.</p>
	  </div>
	</div>
  
	<div class="checklist-subcontainer"> 
  
	  <div class="checklist-heading">
	      <p>General</p>
	      <p class="help">WARNING: Where short circuit currents are required, follow AS/NZS 5033 Appendix D for the steps that shall be undertaken to measure the short circuit current safely.</p>
	      <p class="help">NOTE: Some projects require that short circuit currents are recorded as part of the contractual commissioning; otherwise a record of the actual operating current of each string is sufficient. This could be done by using the meter on the inverter or by using a clamp meter when the system is operational.</p>
	      <p>Insulation resistance measurement</p>
	      <p class="help">WARNING: PV array dc circuits are live during daylight and, unlike a conventional ac circuit, cannot be isolated before performing this test. Follow AS/NZS 5033 Appendix D4 for the steps that shall be undertaken to measure the insulation resistance safely.</p>
	  </div>
  
	  <% if @manual.checklist_responses.count == 0 # prevent dupes %>
	    <% @manual.checklist_responses.build ChecklistItem.all.map{|m| {:checklist_item_id => m.id }} %>
	  <% end %>
  
	  <% previous_group_id = nil %>
  
	  <%= f.fields_for :checklist_responses, @manual.checklist_responses.sort_by(&:checklist_item_id) do |b| %>  
    
	    <% if previous_group_id != b.object.checklist_item.checklist_group_id %>
	      <div class="checklist-heading">
			    <p><%= b.object.checklist_item.checklist_group.name %></p>
	        <p class="help"><%= b.object.checklist_item.checklist_group.description.html_safe %></p>
		    </div>
	    <% end %> 
      
	    <% previous_group_id = b.object.checklist_item.checklist_group_id %>
    
  
	    <div class="field checklist">
      
	      <% if b.object.checklist_item %>
      
	      <div class="checklist-label">
          
	          <%= b.label :response, b.object.checklist_item.label %>
      
	      </div>
      
	      <div class="checklist-input">
        
	          <% if b.object.checklist_item.field_type.present? %>
	          
	            <%= b.hidden_field :na, :value => (b.object.na || "false"), :class => 'na-field' %>
	            <%= b.hidden_field :checklist_item_id, :value => b.object.checklist_item.id %>
            
	            <%= b.send(b.object.checklist_item.field_type, :response) %>
          
	            <p class="help"><%= b.object.checklist_item.helper.html_safe %></p>
	            
	            <%= link_to "N/A", "#", :class => 'btn btn-small na-btn' %>
          
	          <% end %>
      
	      </div>
      
	      <% end %>
      
	    </div>
      
	  <% end %>
  
  </div> <!-- checklist sub-container -->
  
</div>

app/views/manuals/_step_inverter.html.erb
<div class="field">
  <div class="field-label">
    <%= f.label :inverter_brand, "Brand" %>
  </div>
  <div class="field-input">
    <%= f.text_field :inverter_brand %>
  </div>
</div>
<div class="field">
  <div class="field-label">
    <%= f.label :inverter_series, "Series" %>
  </div>
  <div class="field-input">
    <%= f.text_field :inverter_series %>
  </div>
</div>
<div class="field">
  <div class="field-label">
    <%= f.label :inverter_model, "Model" %>
  </div>
  <div class="field-input">
    <%= f.text_field :inverter_model %>
  </div>
</div>
<div class="field">
  <div class="field-label">
    <%= f.label :inverter_output, "Output" %>
  </div>
  <div class="field-input input-append">
    <span class="input-container"><%= f.text_field :inverter_output %></span>
    <span class="add-on">kW</span>
  </div>
</div>
<div class="field">
  <div class="field-label">
    <%= f.label :inverter_number, "Number of Inverters" %>
  </div>
  <div class="field-input input-append">
    <span class="input-container"><%= f.text_field :inverter_number %></span>
  </div>
</div>

<div class="field" data-serial-range>
  <%= render 'serial_range' %>
  <div class="field-label">
    <%= f.label :inverter_serial, "Inverter Serial Number" %>
    <p class="helper">Optional - enter here unless published in attachments.</p>
  </div>
  <div class="field-input">
    <%= f.text_area :inverter_serial, :rows => 4, 'data-serial-range-output' => '' %>
  </div>
</div>

app/views/manuals/_step_payment.html.erb
<%= hidden_field_tag :payment, '1' %>
<%= hidden_field_tag :new_card, (current_user.eway_id ? '0' : '1') %>

<%= f.fields_for [:user_attributes, @manual.user] do |b| %>
  
  <div class="field">
    <div class="field-label">&nbsp;</div>
    <div class="field-input">
      Total <strong><%= currency(CASUAL_FEE) %></strong>
    </div>
  </div>
  
  <% if current_user.eway_id %>
    <div class="field">
      <div class="field-label">&nbsp;</div>
      <div class="field-input">
        <p class="regular">Using stored credit card number<br/><strong><%= format_card(current_user.stored_cc_number) %></strong></p>
        <p>
          <%= link_to "Change credit card", "#", :class => "show-cc-fields" %>
          <%= link_to "Use this card", "#", :class => "hide-cc-fields" %>
        </p>
      </div>
    </div>
    
  <% end %>
  
  <div id="subscribe-cc-fields" class="<%= current_user.eway_id ? 'hidden' : '' %>">

    <%= render :partial => "shared/cc_fields", :locals => {f: b} %>
    <div class="field">
      <div class="field-label">
        <%= b.label :remember %>
      </div>
      <div class="field-input">
        <%= b.check_box :remember %> 
        <p class="help">Your details will be stored securely. Read our security policy <%= link_to "here", "/security", :target => :_blank %>.</p>
      </div>
    </div>

  </div>

<% end %>

app/views/manuals/_step_warranties.html.erb
<div class="field">
  <div class="field-label">
    <%= f.label :warranty_workmanship, "Installation Workmanship" %>
  </div>
  <div class="field-input">
    <%= f.text_field :warranty_workmanship, :placeholder => "2 years" %>
  </div>
</div>
<div class="field">
  <div class="field-label">
    <%= f.label :warranty_panels_product, "Panels - Product" %>
  </div>
  <div class="field-input">
    <%= f.text_field :warranty_panels_product, :placeholder => "10 years" %>
  </div>
</div>
<div class="field">
  <div class="field-label">
    <%= f.label :warranty_panels_output_performance, "Panels - Output Performance" %>
  </div>
  <div class="field-input">
    <%= f.text_field :warranty_panels_output_performance, :placeholder => "25 years" %>
  </div>
</div>
<div class="field">
  <div class="field-label">
    <%= f.label :warranty_inverter %>
  </div>
  <div class="field-input">
    <%= f.text_field :warranty_inverter, :placeholder => "5 years" %>
  </div>
</div>

app/views/manuals/index.html.erb
<table class="table" id="manuals-archive-table">
  <tr>
    <th width="20">Paid</th>
    <th>Name</th>
    <th class="hidden-phone">Address</th>
    <th>Install date</th>
    <th></th>
    <th></th>
  </tr>
  <% @manuals.each do |manual| %>
    <%= content_tag :tr, class: (manual.filled ? '': 'incomplete') do %>
      <td class="paid-icon">
        <%= link_to content_tag(:i, "", class: (manual.paid? ? 'icon-ok' : (manual.marked? ? 'icon-tag' : 'icon-minus'))), manual %>
      </td>
      <td><%= link_to manual.client_name, manual %></td>
      <td class="hidden-phone"><%= link_to manual.display_address, manual %></td>
      <td><%= link_to nicetime(manual.install_date), manual %></td>
      <td class="index-controls">
        <%= link_to "Duplicate", manual_duplicate_path(manual) %>         
      </td>
      <td class="index-controls">
        <%= link_to 'Delete', manual, method: :delete, data: { confirm: 'Are you sure?' }, :class => "delete-btn" %></td>
    <% end %>
  <% end %>


</table>

app/views/manuals/installer_signature.html.erb
<p>I verify that the PV system at <%= @manual.client_address %> is installed to all relevant standards.</p>

<%= render :partial => "signature" %>

app/views/manuals/new.html.erb
<p>Get started below by filling in details for the installation.</p>

<%= render 'form' %>

app/views/manuals/show.html.erb
<div id="manual-info">
  <% if @manual.unlocked? %>
    <% if @manual.filled? %>
      <p class="alert">
        Your manual is ready for download. You can now attach PDFs or add images and select a cover image.
        <% if current_user.fields_not_filled? %>
          <br/>You should <%= link_to "fill in all your company details", edit_user_registration_path %> to ensure this manual contains correct information.
        <% end %>
      </p>
      
      <div id="manual-uploads">
        <%= render 'images' %>
        <hr/>
        <%= render 'pdfs_form' %>
      </div>
      
      
      <%= form_for @manual, :url => manual_document_path(@manual, :format => :pdf) do |f| %>
      
        <% if current_user.pdfs.count > 0 %>
        
          <div id="manual-pdfs-boxes">
            
              <h4>Choose documents to attach to this manual</h4>
              
              <%= hidden_field_tag :pdf_list, true %>
              <%= hidden_field_tag 'manual[pdf_ids][]', nil %>

              <% @manual.user.pdfs.each do |pdf| %>
                <p class="pdf">
                  <%= check_box_tag 'manual[pdf_ids][]', pdf.id, @manual.pdf_ids.include?(pdf.id), id: dom_id(pdf), :class => 'pdf-checkbox' %> 
                  <%= label_tag dom_id(pdf), pdf.file_file_name, :class => "checkbox" %>  
                  <%= link_to "Delete", pdf_path(pdf), :method => :delete, :confirm => "Delete #{pdf.file_file_name}?", :class => 'delete-pdf-link' %>
                </p>
              <% end %>
          </div>
          
        <% end %>
          
        <hr/>
        <h3>Attachment Checklist <i class="icon-ok"></i></h3>
        <p class="help">Before downloading your manual be sure to check you have attached the following:</p><br/>
        <% Checklist.all.each do |checklist| %>
        
          <% if checklist.show_check_question || !@manual.include_checklist %>
            <%= check_box_tag "manual[checklist_ids][]", checklist.id, @manual.checklist_ids.include?(checklist.id), id: dom_id(checklist) %>
            <%= label_tag dom_id(checklist), checklist.question.html_safe %><br/>
          <% end %>
          
        <% end %>
        
        <div id="manual-actions">              
          <p>Download your completed manual below</p>
          <button type="submit" class="btn primary" id="download-pdf">
            <i class='icon-download-alt'></i> Download Manual
          </button>
        </div>
      
      
      <% end %>
      
    <% end %>
  <% end %>
</div>

<%= render 'form' %>

app/views/manuals/signature_success.html.erb
<div id="signature-success">
  <p><i class="icon-ok"></i> Thanks!</p>
</div>

<script type="text/javascript">
  setTimeout(function(){
    window.close();
  }, 3000);
</script>

app/views/manuals/update.js.erb
var div = $("#manual-images");
var images = "<% @manual.images.each do |image| %><%= escape_javascript(render(:partial => 'manuals/image', :locals => { image: image })) %><% end %>";
div.html(images);
$("#manual-images-container").removeClass("loading").spin(false);