config/routes.rb
Solar::Application.routes.draw do

  resources :checklist_items

  devise_for :users
  
  resources :users, only: [:show, :update] do
    collection do 
      get :billing
      get :subscribe
      put :create_subscription
      put :unsubscribe
      get :edit_card
      put :update_card
      post :read_message
    end
  end

  resources :manuals do
    post :single_charge
    get :duplicate
    get :installer_signature
    get :contractor_signature
    get :signature_success
  end
  
  resources :invoices, :controller => "eway_payments", :only => [:show]
  
  resources :eway_payments, only: [:create]
  
  resources :images, only: [:destroy]
  resources :pdfs, only: [:destroy]
  
  put '/manuals/:id/document', to: 'manuals#document', as: "manual_document"
  
  put '/images/:id/set_feature', :to => 'images#set_feature', :as => 'set_feature'
  
  authenticated :user do
    root :to => "manuals#new"
  end
  
  get '/faq', to: 'home#faq'  
  get '/privacy', to: 'home#privacy'
  get '/delivery', to: 'home#delivery'
  get '/refunds', to: 'home#refunds'
  get '/terms', to: 'home#terms'
  get '/admin_info', to: 'admin#admin_info'

  root :to => 'home#index'

end

app/models/checklist_item.rb
class ChecklistItem < ActiveRecord::Base

  attr_accessible :checklist_group_id, :label, :helper, :field_type, :image_url
  has_many :checklist_responses, :dependent => :destroy
  has_many :manuals, :through => :checklist_responses
  belongs_to :checklist_group
  
end

app/controllers/checklist_items_controller.rb
class ChecklistItemsController < ApplicationController
  before_filter :authenticate_user!
  # GET /checklist_items
  # GET /checklist_items.json
  def index
    @checklist_items = ChecklistItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @checklist_items }
    end
  end

  # GET /checklist_items/1
  # GET /checklist_items/1.json
  def show
    @checklist_item = ChecklistItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @checklist_item }
    end
  end

  # GET /checklist_items/new
  # GET /checklist_items/new.json
  def new
    @checklist_item = ChecklistItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @checklist_item }
    end
  end

  # GET /checklist_items/1/edit
  def edit
    @checklist_item = ChecklistItem.find(params[:id])
  end

  # POST /checklist_items
  # POST /checklist_items.json
  def create
    @checklist_item = ChecklistItem.new(params[:checklist_item])

    respond_to do |format|
      if @checklist_item.save
        format.html { redirect_to @checklist_item, notice: 'Checklist item was successfully created.' }
        format.json { render json: @checklist_item, status: :created, location: @checklist_item }
      else
        format.html { render action: "new" }
        format.json { render json: @checklist_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /checklist_items/1
  # PUT /checklist_items/1.json
  def update
    @checklist_item = ChecklistItem.find(params[:id])

    respond_to do |format|
      if @checklist_item.update_attributes(params[:checklist_item])
        format.html { redirect_to @checklist_item, notice: 'Checklist item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @checklist_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checklist_items/1
  # DELETE /checklist_items/1.json
  def destroy
    @checklist_item = ChecklistItem.find(params[:id])
    @checklist_item.destroy

    respond_to do |format|
      format.html { redirect_to checklist_items_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/checklist_items_helper.rb
module ChecklistItemsHelper
end

app/views/checklist_items/_form.html.erb
<%= form_for(@checklist_item) do |f| %>
  <% if @checklist_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@checklist_item.errors.count, "error") %> prohibited this checklist_item from being saved:</h2>

      <ul>
      <% @checklist_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :checklist_group_id %><br />
    <%= f.number_field :checklist_group_id %>
  </div>
  <div class="field">
    <%= f.label :label %><br />
    <%= f.text_area :label %>
  </div>
  <div class="field">
    <%= f.label :helper %><br />
    <%= f.text_field :helper %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/checklist_items/edit.html.erb
<h1>Editing checklist_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @checklist_item %> |
<%= link_to 'Back', checklist_items_path %>

app/views/checklist_items/index.html.erb
<h1>Listing checklist_items</h1>

<table>
  <tr>
    <th>Checklist group</th>
    <th>Label</th>
    <th>Helper</th>
    <th>Type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @checklist_items.each do |checklist_item| %>
  <tr>
    <td><%= checklist_item.checklist_group_id %></td>
    <td><%= checklist_item.label %></td>
    <td><%= checklist_item.helper %></td>
    <td><%= checklist_item.type %></td>
    <td><%= link_to 'Show', checklist_item %></td>
    <td><%= link_to 'Edit', edit_checklist_item_path(checklist_item) %></td>
    <td><%= link_to 'Destroy', checklist_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Checklist item', new_checklist_item_path %>

app/views/checklist_items/new.html.erb
<h1>New checklist_item</h1>

<%= render 'form' %>

<%= link_to 'Back', checklist_items_path %>

app/views/checklist_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Checklist group:</b>
  <%= @checklist_item.checklist_group_id %>
</p>

<p>
  <b>Label:</b>
  <%= @checklist_item.label %>
</p>

<p>
  <b>Helper:</b>
  <%= @checklist_item.helper %>
</p>

<p>
  <b>Type:</b>
  <%= @checklist_item.type %>
</p>


<%= link_to 'Edit', edit_checklist_item_path(@checklist_item) %> |
<%= link_to 'Back', checklist_items_path %>