config/routes.rb
Solar::Application.routes.draw do

  resources :checklist_items

  devise_for :users
  
  resources :users, only: [:show, :update] do
    collection do 
      get :billing
      get :subscribe
      put :create_subscription
      put :unsubscribe
      get :edit_card
      put :update_card
      post :read_message
    end
  end

  resources :manuals do
    post :single_charge
    get :duplicate
    get :installer_signature
    get :contractor_signature
    get :signature_success
  end
  
  resources :invoices, :controller => "eway_payments", :only => [:show]
  
  resources :eway_payments, only: [:create]
  
  resources :images, only: [:destroy]
  resources :pdfs, only: [:destroy]
  
  put '/manuals/:id/document', to: 'manuals#document', as: "manual_document"
  
  put '/images/:id/set_feature', :to => 'images#set_feature', :as => 'set_feature'
  
  authenticated :user do
    root :to => "manuals#new"
  end
  
  get '/faq', to: 'home#faq'  
  get '/privacy', to: 'home#privacy'
  get '/delivery', to: 'home#delivery'
  get '/refunds', to: 'home#refunds'
  get '/terms', to: 'home#terms'
  get '/admin_info', to: 'admin#admin_info'

  root :to => 'home#index'

end

app/views/layouts/_footer.html.erb
<div id="footer">
    
      <% if !user_signed_in? %>
      
      <div id="contact" class="greenfooter">
        <footer class="inner-container homefooter">
          <div class="foot3">For<br/>Support<br/>Enquiries<br/>Questions</div>
          <div class="foot1"><i class="sm-sprite sm-curly"></i></div>
          <div class="foot4  arrow-down"><i class="icon-arrow-down icon-white">&nbsp;</i></div>
          <div class="foot4">Contact Us<i class="icon-white icon-comment"></i><br/><a href="mailto:info@solarmanuals.com.au">info@solarmanuals.com.au</a></div>       
        </footer>
      </div>    
      
      <% end %>
              
       <div class="blackfooter">
        <footer class="homefooter">
          <div class="foot8">
            <ul>
              <li><%= link_to "Terms & Conditions", '/terms' %></li>
              <li><%= link_to "Privacy", '/privacy' %></li>
              <li><%= link_to "FAQ", '/faq' %></li>
            </ul>
          </div>
          
          <div class="foot4">
            <% if user_signed_in? %>
            <p>
              Contact Us <i class="icon-white icon-comment">&nbsp;</i> <a href="mailto:info@solarmanuals.com.au">info@solarmanuals.com.au</a>
            </p>
            <% end %>
            <p class="help">&copy; Solar Energy Consultants Australia 2013<br/>All prices on this site are stated in Australian Dollars and include GST.</p>
          </div>
        </footer>
      </div>
    
</div>


  <%= javascript_include_tag "application" %>
  
  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-39278466-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
  
  </body>
</html>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<!--[if lt IE 9 ]> <html class="shit" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html class="notshit" lang="en"> <!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Solar Installer Technologies" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%# favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%# favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%# favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%# favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.png', :rel => 'shortcut icon' %>
  </head>
  
  <body class="<%= user_signed_in? ? 'signed-in' : '' %> <%= params[:controller] %> <%= params[:action] %>">
    

app/views/layouts/_signed_in_nav.html.erb
<div id="signed-in-top" class="nest">

  <div id="identity">
    <%= render "users/logo" %>
  </div>

  <div id="user-details">
    <div class="user-icon"><i class="icon-user"></i></div>
    <div class="user-deets">
      <p>
        <strong><%= current_user.full_name %></strong><br/>
        <%= current_user.company %><br/>
        <%= current_user.full_address %><br/>
        <%= link_to "Account Details", edit_user_registration_path %>
      </p>
    </div>
  </div>

  <div id="billing-info">

    <div class="bill-icon"><i class="icon-file-alt"></i></div>

    <div class="bill-deets">
    <% if current_user.insider %>
      <p>Insider Account</p>
    <% elsif current_user.subscribed? %>
      <p>
        <strong>Subscribed</strong>&nbsp;&nbsp;∙&nbsp;&nbsp;<%= link_to "Billing Details", billing_users_path %><br/>
        Usage <strong><%= currency(current_user.current_charge) %></strong><br/>
        Next charge <strong><%= nicetime(current_user.last_payed_at + 1.month) %></strong>
      </p>

    <% else %>
        <p>
          <strong>Casual User</strong><br/>
          <strong><%= currency(CASUAL_FEE) %> <span class="help">Per Manual</span></strong><br/><br/>
          <%= link_to "Billing Details", billing_users_path %>
        </p>
    <% end %>
    </div>
  </div>

  <div id="signout-holder">
    <%= link_to destroy_user_session_path, :method => :delete, :id => "sign-out" do %>
      Sign Out <i class="icon-signout icon-white"></i>
    <% end %>
  </div>

</div>

<div id="user-menu">
  <%= nav_link "New Manual", root_path %>
  <%= nav_link "My Installs (#{current_user.active_manuals.count})", manuals_path %>
</div>

app/views/layouts/application.html.erb
<%= render "layouts/header" %>
<div class="wrap">
  <div class="inner-wrap">
    
    <%= render 'shared/flash', { flash: flash } %>
    
    <% if user_signed_in? %>
    <%= render "shared/ie_notice" %>
      <div class="container">
        <%= render 'layouts/signed_in_nav' %>
      </div>
    <% end %>
  
    <div class="container content">
  
      <%= yield %>
    
    </div> <!-- /container -->
  
    <div id="push"></div>
  </div>
</div>

<%= render "layouts/footer" %>

app/views/layouts/blank.html.erb
<%= render 'layouts/header' %>

  <div class="wrap">
    <div class="inner-wrap">
      <div class="container">
        <div class="inner-container">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
  
  <%= javascript_include_tag "blank" %>
  
  </body>
</html>

app/views/layouts/home.html.erb
<%= render "layouts/header" %>

  <div class="wrap">
    <div id="header" class="inner-wrap fluid">
        <div id="home-nav" class="container">
          <div class="inner-container">
            <ul id="home-menu">
              <li id="logo"><h1><a href="/">Installer Technologies</a></h1></li>
              <ul>
                <li><a href="/#features" class="scroll">Features</a></li>
                <li><a href="/#pricing" class="scroll">Pricing</a></li>
                <li><a href="/#sample" class="scroll">Sample</a></li>
                <li><a href="/#contact" class="scroll">Contact</a></li>
                <li><a href="/users/sign_up" class="get_started">Try It Free</a></li>
                <li id="sign-in"><%= link_to new_user_session_path do %>Sign In<i class="icon-user"></i><%end%></li>
              </ul>
            </ul>
          </div>
      </div>
    </div>
    
      <%= render 'shared/flash', { flash: flash } %> 
    
      <%= yield %>
          
    <div id="push"></div>
  </div>

<%= render "layouts/footer" %>